/**
 * 파일명: downloadFile.ts
 * 
 * 파일 용도:
 * 파일 다운로드 유틸리티 함수
 * - Blob 데이터를 파일로 다운로드
 * - createObjectURL을 사용한 다운로드 트리거
 * - 파일명 자동 생성
 */

/** 지원하는 내보내기 형식 */
export type ExportFormat = 'pdf' | 'html' | 'hwp';

/** 형식별 MIME 타입 매핑 */
const MIME_TYPES: Record<ExportFormat, string> = {
  pdf: 'application/pdf',
  html: 'text/html',
  hwp: 'application/x-hwp',
};

/** 형식별 파일 확장자 매핑 */
const FILE_EXTENSIONS: Record<ExportFormat, string> = {
  pdf: '.pdf',
  html: '.html',
  hwp: '.hwp',
};

/**
 * Blob 데이터를 파일로 다운로드
 * 
 * @param {Blob} blob - 다운로드할 Blob 데이터
 * @param {string} filename - 저장할 파일명
 */
export const downloadBlob = (blob: Blob, filename: string): void => {
  // Object URL 생성
  const url = window.URL.createObjectURL(blob);
  
  // 다운로드 링크 생성 및 클릭
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  // 정리
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

/**
 * 내보내기 파일명 생성
 * 
 * @param {string} projectName - 프로젝트명
 * @param {ExportFormat} format - 내보내기 형식
 * @param {number} version - 버전 번호 (optional)
 * @returns {string} 생성된 파일명 (예: "테스트_사업계획서_v1.pdf")
 */
export const generateExportFilename = (
  projectName: string,
  format: ExportFormat,
  version?: number
): string => {
  // 파일명에 사용할 수 없는 문자 제거
  const sanitizedName = projectName.replace(/[\\/:*?"<>|]/g, '_');
  const versionSuffix = version ? `_v${version}` : '';
  const extension = FILE_EXTENSIONS[format];
  
  return `${sanitizedName}_사업계획서${versionSuffix}${extension}`;
};

/**
 * 형식에 맞는 MIME 타입 반환
 * 
 * @param {ExportFormat} format - 내보내기 형식
 * @returns {string} MIME 타입
 */
export const getMimeType = (format: ExportFormat): string => {
  return MIME_TYPES[format];
};

/**
 * Mock 문서 데이터 생성 (개발용)
 * 실제 환경에서는 백엔드 API에서 Blob을 받아옴
 * 
 * @param {ExportFormat} format - 내보내기 형식
 * @param {string} content - 문서 내용
 * @returns {Blob} 생성된 Blob
 */
export const createMockDocument = (
  format: ExportFormat,
  content: string
): Blob => {
  const mimeType = getMimeType(format);
  
  if (format === 'html') {
    const htmlContent = `
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>사업계획서</title>
  <style>
    body { font-family: 'Malgun Gothic', sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #22c55e; padding-bottom: 10px; }
    h2 { color: #333; margin-top: 30px; }
    p { line-height: 1.8; color: #444; }
    .section { margin-bottom: 40px; }
    .footer { margin-top: 60px; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  ${content}
  <div class="footer">
    <p>Generated by BizPlan AI - ${new Date().toLocaleDateString('ko-KR')}</p>
  </div>
</body>
</html>`;
    return new Blob([htmlContent], { type: mimeType });
  }
  
  // PDF/HWP는 실제로는 바이너리 형식이지만, Mock에서는 텍스트로 처리
  // 실제 환경에서는 백엔드에서 생성된 Blob을 사용
  return new Blob([content], { type: mimeType });
};

export default {
  downloadBlob,
  generateExportFilename,
  getMimeType,
  createMockDocument,
};

